### PR TITLE
No dep graph

### PR DESCRIPTION
**Pull request by sokrahta**
sbt-dependency-graph plugin interferes with other plugins.
included *safely* in socrata-sbt-plugins instead.

[Review on Reviewable](https://reviewable.io/reviews/socrata/socrata-cloudbees-sbt/7)

### CODE REVIEW

**Comment by kaidamasaki** [comment]
It's cool that Reviewable looks like it's hooked into this.

**Comment by kaidamasaki** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/socrata-cloudbees-sbt/7)



---

And that comments from Github show up on Reviewable.

---

**Comment by kaidamasaki** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/socrata-cloudbees-sbt/7)







---

<sup>**[.gitignore, line 5 \[r1\]](https://reviewable.io:443/reviews/socrata/socrata-cloudbees-sbt/7#-JhKtmvm6zFfjyBHj5Me)** ([raw file](https://github.com/socrata/socrata-cloudbees-sbt/blob/0c359759fa2e31443ba08701ba5c34aa1deac80c/.gitignore#L5)):</sup>
Line comments don't integrate?  

Also, you can probably configure your editor to include trailing newlines. 

---

**Comment by kaidamasaki** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/socrata-cloudbees-sbt/7)



---

LGTM.

---

**Comment by velvia** [comment]
It would be awesome to publish this on maven central or somewhere to be
used outside of Socrata projects too.

On Wed, Feb 4, 2015 at 11:45 AM, Kaida Masaki <notifications@github.com>
wrote:

> Merged #7 <https://github.com/socrata/socrata-cloudbees-sbt/pull/7>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socrata/socrata-cloudbees-sbt/pull/7#event-230291186>.
>



-- 
Evan Chan   |   Principal Engineer, Socrata     |    @evanfchan
*Socrata <http://www.socrata.com/> *| The Data Experience Company™
*Socrata isn't about worldly success, but about changing the world
successfully. This is why I'm excited to be here.*
*What does Socrata do? <https://www.youtube.com/watch?v=yyz86MlkriQ> *(watch
our 2 min video)

**Comment by sokrahta** [comment]
I saw that we have some artifacts published on [maven central](http://search.maven.org/#search|ga|1|socrata) already, could follow the same release steps to achieve that.

**Pull request merged**
